#!/usr/bin/env bash
set -euo pipefail

EXPECTED_PROJECT_ID="morning-brew-slideshow-052126"
EXPECTED_AUTH_DOMAIN="morning-brew-slideshow-052126.firebaseapp.com"
EXPECTED_STORAGE_BUCKET="morning-brew-slideshow-052126.firebasestorage.app"
EXPECTED_MESSAGING_SENDER_ID="636053437401"
EXPECTED_APP_ID="1:636053437401:web:4df1e4f84b6562091f37c8"

missing=0
for var in VITE_FIREBASE_API_KEY VITE_FIREBASE_AUTH_DOMAIN VITE_FIREBASE_PROJECT_ID \
  VITE_FIREBASE_STORAGE_BUCKET VITE_FIREBASE_MESSAGING_SENDER_ID VITE_FIREBASE_APP_ID; do
  if [ -z "${!var:-}" ]; then
    echo "ERROR: $var is not set"
    missing=1
  fi
done

if [ "$missing" -ne 0 ]; then
  exit 1
fi

if [ "$VITE_FIREBASE_PROJECT_ID" != "$EXPECTED_PROJECT_ID" ]; then
  echo "ERROR: VITE_FIREBASE_PROJECT_ID must be $EXPECTED_PROJECT_ID (got: $VITE_FIREBASE_PROJECT_ID)"
  exit 1
fi

if [ "$VITE_FIREBASE_AUTH_DOMAIN" != "$EXPECTED_AUTH_DOMAIN" ]; then
  echo "ERROR: VITE_FIREBASE_AUTH_DOMAIN must be $EXPECTED_AUTH_DOMAIN (got: $VITE_FIREBASE_AUTH_DOMAIN)"
  exit 1
fi

if [ "$VITE_FIREBASE_STORAGE_BUCKET" != "$EXPECTED_STORAGE_BUCKET" ]; then
  echo "ERROR: VITE_FIREBASE_STORAGE_BUCKET must be $EXPECTED_STORAGE_BUCKET (got: $VITE_FIREBASE_STORAGE_BUCKET)"
  exit 1
fi

if [ "$VITE_FIREBASE_MESSAGING_SENDER_ID" != "$EXPECTED_MESSAGING_SENDER_ID" ]; then
  echo "ERROR: VITE_FIREBASE_MESSAGING_SENDER_ID must be $EXPECTED_MESSAGING_SENDER_ID (got: $VITE_FIREBASE_MESSAGING_SENDER_ID)"
  exit 1
fi

if [ "$VITE_FIREBASE_APP_ID" != "$EXPECTED_APP_ID" ]; then
  echo "ERROR: VITE_FIREBASE_APP_ID must be $EXPECTED_APP_ID (got: $VITE_FIREBASE_APP_ID)"
  exit 1
fi

echo "Firebase env matches $EXPECTED_PROJECT_ID"
